#!/bin/bash

if [[ "$1" == "/bin" || "$1" == "bin" ]]; then
    echo "=== /bin ==="
    echo "-> Details: Binaries. Contains Essential binaries and executables."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "============"

elif [[ $1 == "/boot" || $1 == "boot" ]]; then
    echo "=== /boot ==="
    echo "-> Details: Static files of the boot loader."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "-> Sub-Directories: grub/"
    echo "============="

elif [[ $1 == "/dev" || $1 == "dev" ]]; then
    echo "=== /dev ==="
    echo "-> Details: Device files (like USB, HDD, SSD)."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "-> Files: /dev/sda, /dev/sdb, etc..."
    echo "============"

elif [[ $1 == "/etc" || $1 == "etc" ]]; then
    echo "=== /etc ==="
    echo "-> Details: Et cetera. Host specific system configuration files and directories."
    echo "-> Permissions: (or) "
    echo "-> Sub-Directories: /etc/opt/, /etc/X11/, ..."
    echo "-> Files: passwd, group, hosts, etc..."
    echo "============"

elif [[ $1 == "/home" || $1 == "home" ]]; then
    echo "=== /home ==="
    echo "-> Details: User home directories. User specific configuration files are stored here."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "-> Sub-Directories: user1/, user2/, etc..."
    echo "============="

elif [[ $1 == "/lib" || $1 == "lib" || $1 == "/lib32" ]]; then
    echo "=== /lib ==="
    echo "-> Details: Libraries. Essential shared libraries and kernel modules."
    echo "-> Permissions: rwxrwxrwx (or) 777"
    echo "============"

elif [[ $1 == "/media" || $1 == "media" || $1 == "/run/media" || $1 == "/run/media/" ]]; then
    echo "=== /media ==="
    echo "-> Details: Mount point for removeable media."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "-> Sub-Directories: /media/user1/usb-device, etc..."
    echo "=============="

elif [[ $1 == "/mnt" || $1 == "mnt" ]]; then
    echo "=== /mnt ==="
    echo "-> Details: Mount. Mount point for mounting a filesystem temporarily."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "-> Sub-Directories: /mnt/usb-device, etc..."
    echo "============"

elif [[ $1 == "/run" || $1 == "run" ]]; then
    echo "=== /run ==="
    echo "-> Details: Used to store temporary files. Cleared on reboot."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "============"

elif [[ $1 == "/root" || $1 == "root" ]]; then
    echo "=== /root ==="
    echo "-> Details: Home directory for root users."
    echo "-> Permissions: rwxr-x--- (or) 750"
    echo "============"

elif [[ $1 == "/opt" || $1 == "opt" ]]; then
    echo "=== /opt ==="
    echo "-> Details: Optional. Add-ons of application software packages."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "============"

elif [[ $1 == "/sbin" || $1 == "sbin" ]]; then
    echo "=== /sbin ==="
    echo "-> Details: System binaries. Essential system binaries (usually root)."
    echo "-> Permissions: rwxrwxrwx (or) 777"
    echo "-> Files: shutdown"
    echo "============="

elif [[ $1 == "/srv" || $1 == "srv" ]]; then
    echo "=== /srv ==="
    echo "-> Details: Service. Data for services provided by this system."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "============"

elif [[ $1 == "/sys" || $1 == "sys" ]]; then
    echo "=== /sys ==="
    echo "-> Details: System hardware and kernel information."
    echo "-> Permissions: r-xr-xr-x (or) 555"
    echo "============"

elif [[ $1 == "/usr" || $1 == "usr" ]]; then
    echo "=== /usr ==="
    echo "-> Details: Location of user programs, files and documentation. Shareable and read-only."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "-> Sub-Directories: bin/ include/ lib/ local/ sbin/ share/"
    echo "============"

elif [[ $1 == "/usr/bin" || $1 == "usr/bin" || $1 == "usr/bin/" || $1 == "/usr/bin" ]]; then
    echo "=== /usr/bin ==="
    echo "-> Details: User binaries."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "================"

elif [[ $1 == "/usr/include" || $1 == "usr/include" || $1 == "usr/include/" || $1 == "/usr/include" ]]; then
    echo "=== /usr/include ==="
    echo "-> Details: Header files for C language."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "===================="

elif [[ $1 == "/usr/lib" || $1 == "usr/lib" || $1 == "usr/lib/" || $1 == "/usr/lib" ]]; then
    echo "=== /usr/lib ==="
    echo "-> Details: Libraries."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "===================="

elif [[ $1 == "/usr/local" || $1 == "usr/local" || $1 == "usr/local/" || $1 == "/usr/local" ]]; then
    echo "=== /usr/local ==="
    echo "-> Details: Local hierarchy"
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "=================="

elif [[ $1 == "/usr/sbin" || $1 == "usr/sbin" || $1 == "usr/sbin/" || $1 == "/usr/sbin" ]]; then
    echo "=== /usr/sbin ==="
    echo "-> Details: Non-vital system binaries"
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "================="

elif [[ $1 == "/usr/share" || $1 == "usr/share" || $1 == "usr/share/" || $1 == "/usr/share" ]]; then
    echo "=== /usr/share ==="
    echo "-> Details: Architecture-independent data"
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "=================="

elif [[ $1 == "/var" || $1 == "var" ]]; then
    echo "=== /var ==="
    echo "-> Details: Variable data. Changes during system operation. Not shareable."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "-> Sub-Directories: /var/log/, /var/spool/, /var/tmp/, /var/cache/, /var/lock/"
    echo "============"

elif [[ $1 == "/var/cache" || $1 == "var/cache" || $1 == "var/cache/" || $1 == "/var/cache" ]]; then
    echo "=== /var/cache ==="
    echo "-> Details: Application cache data."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "=================="

elif [[ $1 == "/var/spool" || $1 == "var/spool" || $1 == "var/spool/" || $1 == "/var/spool" ]]; then
    echo "=== /var/spool ==="
    echo "-> Details: Application spool data."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "=================="

elif [[ $1 == "/var/tmp" || $1 == "var/tmp" || $1 == "var/tmp/" || $1 == "/var/tmp" ]]; then
    echo "=== /var/tmp ==="
    echo "-> Details: Temporary files preseved between reboots."
    echo "-> Permissions: rwxrwxrwt (or) 1777"
    echo "================"

elif [[ $1 == "/var/log" || $1 == "var/log" || $1 == "var/log/" || $1 == "/var/log" ]]; then
    echo "=== /var/log ==="
    echo "-> Details: Log files and directories."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "================"

elif [[ $1 == "/var/opt" || $1 == "var/opt" || $1 == "var/opt/" || $1 == "/var/opt" ]]; then
    echo "=== /var/opt ==="
    echo "-> Details: Variable optional data."
    echo "-> Permissions: rwxr-xr-x (or) 755"
    echo "================"

elif [[ $1 == "/var/run" || $1 == "var/run" || $1 == "var/run/" || $1 == "/var/run" ]]; then
    echo "=== /var/run ==="
    echo "-> Details: Variable runtime data."
    echo "-> Permissions: rwxrwxrwx (or) 777"
    echo "================"
    
elif [[ $1 == "/proc" || $1 == "proc" ]]; then
    echo "=== /proc ==="
    echo "-> Details: Virtual filesystem for accessing process and kernel-related information."
    echo "-> Permissions: r-xr-xr-x (or) 555"
    echo "============="

else
    echo "======= Available information ======="
    echo "/bin /boot /dev /etc /home /lib"
    echo "/mnt /opt /root /run /sbin /srv"
    echo "/sys /tmp /proc /usr/bin /usr/lib"
    echo "/usr/include /usr/local /usr/sbin"
    echo "/usr/share /var /var/cache /var/spool"
    echo "/var/tmp /var/log /var/opt /var/run"
    echo "====================================="
fi
