#!/bin/sh

if [ "$1" = "/bin" -o "$1" = "bin" ]; then
    echo -e "=== /bin ==="
    echo -e "-> Details: Binaries. Contains Essential binaries and executables."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "============"

elif [[ $1 == "/boot" || $1 == "boot" ]]; then
    echo -e "=== /boot ==="
    echo -e "-> Details: Static files of the boot loader."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "-> Sub-Directories: grub/"
    echo -e "============="

elif [[ $1 == "/dev" || $1 == "dev" ]]; then
    echo -e "=== /dev ==="
    echo -e "-> Details: Device files (like USB, HDD, SSD)."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "-> Files: /dev/sda, /dev/sdb, etc..."
    echo -e "============"

elif [[ $1 == "/etc" || $1 == "etc" ]]; then
    echo -e "=== /etc ==="
    echo -e "-> Details: Et cetera. Host specific system configuration files and directories."
    echo -e "-> Permissions: (or) "
    echo -e "-> Sub-Directories: /etc/opt/, /etc/X11/, ..."
    echo -e "-> Files: passwd, group, hosts, etc..."
    echo -e "============"

elif [[ $1 == "/home" || $1 == "home" ]]; then
    echo -e "=== /home ==="
    echo -e "-> Details: User home directories. User specific configuration files are stored here."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "-> Sub-Directories: user1/, user2/, etc..."
    echo -e "============="

elif [[ $1 == "/lib" || $1 == "lib" || $1 == "/lib32" ]]; then
    echo -e "=== /lib ==="
    echo -e "-> Details: Libraries. Essential shared libraries and kernel modules."
    echo -e "-> Permissions: rwxrwxrwx (or) 777"
    echo -e "============"

elif [[ $1 == "/media" || $1 == "media" || $1 == "/run/media" || $1 == "/run/media/" ]]; then
    echo -e "=== /media ==="
    echo -e "-> Details: Mount point for removeable media."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "-> Sub-Directories: /media/user1/usb-device, etc..."
    echo -e "=============="

elif [[ $1 == "/mnt" || $1 == "mnt" ]]; then
    echo -e "=== /mnt ==="
    echo -e "-> Details: Mount. Mount point for mounting a filesystem temporarily."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "-> Sub-Directories: /mnt/usb-device, etc..."
    echo -e "============"

elif [[ $1 == "/run" || $1 == "run" ]]; then
    echo -e "=== /run ==="
    echo -e "-> Details: Used to store temporary files. Cleared on reboot."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "============"

elif [[ $1 == "/root" || $1 == "root" ]]; then
    echo -e "=== /root ==="
    echo -e "-> Details: Home directory for root users."
    echo -e "-> Permissions: rwxr-x--- (or) 750"
    echo -e "============"

elif [[ $1 == "/opt" || $1 == "opt" ]]; then
    echo -e "=== /opt ==="
    echo -e "-> Details: Optional. Add-ons of application software packages."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "============"

elif [[ $1 == "/sbin" || $1 == "sbin" ]]; then
    echo -e "=== /sbin ==="
    echo -e "-> Details: System binaries. Essential system binaries (usually root)."
    echo -e "-> Permissions: rwxrwxrwx (or) 777"
    echo -e "-> Files: shutdown"
    echo -e "============="

elif [[ $1 == "/srv" || $1 == "srv" ]]; then
    echo -e "=== /srv ==="
    echo -e "-> Details: Service. Data for services provided by this system."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "============"

elif [[ $1 == "/sys" || $1 == "sys" ]]; then
    echo -e "=== /sys ==="
    echo -e "-> Details: System hardware and kernel information."
    echo -e "-> Permissions: r-xr-xr-x (or) 555"
    echo -e "============"

elif [[ $1 == "/usr" || $1 == "usr" ]]; then
    echo -e "=== /usr ==="
    echo -e "-> Details: Location of user programs, files and documentation. Shareable and read-only."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "-> Sub-Directories: bin/ include/ lib/ local/ sbin/ share/"
    echo -e "============"

elif [[ $1 == "/usr/bin" || $1 == "usr/bin" || $1 == "usr/bin/" || $1 == "/usr/bin" ]]; then
    echo -e "=== /usr/bin ==="
    echo -e "-> Details: User binaries."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "================"

elif [[ $1 == "/usr/include" || $1 == "usr/include" || $1 == "usr/include/" || $1 == "/usr/include" ]]; then
    echo -e "=== /usr/include ==="
    echo -e "-> Details: Header files for C language."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "===================="

elif [[ $1 == "/usr/lib" || $1 == "usr/lib" || $1 == "usr/lib/" || $1 == "/usr/lib" ]]; then
    echo -e "=== /usr/lib ==="
    echo -e "-> Details: Libraries."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "===================="

elif [[ $1 == "/usr/local" || $1 == "usr/local" || $1 == "usr/local/" || $1 == "/usr/local" ]]; then
    echo -e "=== /usr/local ==="
    echo -e "-> Details: Local hierarchy"
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "=================="

elif [[ $1 == "/usr/sbin" || $1 == "usr/sbin" || $1 == "usr/sbin/" || $1 == "/usr/sbin" ]]; then
    echo -e "=== /usr/sbin ==="
    echo -e "-> Details: Non-vital system binaries"
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "================="

elif [[ $1 == "/usr/share" || $1 == "usr/share" || $1 == "usr/share/" || $1 == "/usr/share" ]]; then
    echo -e "=== /usr/share ==="
    echo -e "-> Details: Architecture-independent data"
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "=================="

elif [[ $1 == "/var" || $1 == "var" ]]; then
    echo -e "=== /var ==="
    echo -e "-> Details: Variable data. Changes during system operation. Not shareable."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "-> Sub-Directories: /var/log/, /var/spool/, /var/tmp/, /var/cache/, /var/lock/"
    echo -e "============"

elif [[ $1 == "/var/cache" || $1 == "var/cache" || $1 == "var/cache/" || $1 == "/var/cache" ]]; then
    echo -e "=== /var/cache ==="
    echo -e "-> Details: Application cache data."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "=================="

elif [[ $1 == "/var/spool" || $1 == "var/spool" || $1 == "var/spool/" || $1 == "/var/spool" ]]; then
    echo -e "=== /var/spool ==="
    echo -e "-> Details: Application spool data."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "=================="

elif [[ $1 == "/var/tmp" || $1 == "var/tmp" || $1 == "var/tmp/" || $1 == "/var/tmp" ]]; then
    echo -e "=== /var/tmp ==="
    echo -e "-> Details: Temporary files preseved between reboots."
    echo -e "-> Permissions: rwxrwxrwt (or) 1777"
    echo -e "================"

elif [[ $1 == "/var/log" || $1 == "var/log" || $1 == "var/log/" || $1 == "/var/log" ]]; then
    echo -e "=== /var/log ==="
    echo -e "-> Details: Log files and directories."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "================"

elif [[ $1 == "/var/opt" || $1 == "var/opt" || $1 == "var/opt/" || $1 == "/var/opt" ]]; then
    echo -e "=== /var/opt ==="
    echo -e "-> Details: Variable optional data."
    echo -e "-> Permissions: rwxr-xr-x (or) 755"
    echo -e "================"

elif [[ $1 == "/var/run" || $1 == "var/run" || $1 == "var/run/" || $1 == "/var/run" ]]; then
    echo -e "=== /var/run ==="
    echo -e "-> Details: Variable runtime data."
    echo -e "-> Permissions: rwxrwxrwx (or) 777"
    echo -e "================"

else
    echo -e "======= Available information ======="
    echo -e "/bin /boot /dev /etc /home /lib"
    echo -e "/mnt /opt /root /run /sbin /srv"
    echo -e "/sys /tmp /usr/bin /usr/include"
    echo -e "/usr/lib /usr/local /usr/sbin"
    echo -e "/usr/share /var /var/cache /var/spool"
    echo -e "/var/tmp /var/log /var/opt /var/run"
    echo -e "====================================="
fi
